name: Backend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "starter/backend/**"

  workflow_dispatch:

jobs:
  lint:
    name: Backend Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter/backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Run lint
        run: pipenv run lint

  test:
    name: Backend Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter/backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Run tests
        run: pipenv run test
